config/routes.rb
AcreCare::Application.routes.draw do

  devise_for :admins

  resources :donations


  resources :parcels

  root :to => "parcels#index"

  match "/thanks" => "pages#thanks"
  match "/certificate" => "pages#certificate"
  match "/ecard" => "pages#ecard"
  match "/about" =>"pages#about"
  match "/donate" => "pages#donate"

end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
  attr_accessible :description, :short_description, :icon, :title, :latitude, :longitude, :imagename
end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index,:show]

  # GET /parcels
  # GET /parcels.json
  def index
    @parcels = Parcel.all
    cookies[:parcel] = ''
    cookies[:donation] = ''

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parcels }
    end
  end

  # GET /parcels/1
  # GET /parcels/1.json
  def show
    @parcel = Parcel.find(params[:id])
    cookies[:parcel] = params[:id]

    respond_to do |format|
      format.html #{ render :layout => false }
      format.json { render json: @parcel }
    end
  end

  # GET /parcels/new
  # GET /parcels/new.json
  def new
    @parcel = Parcel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @parcel }
    end
  end

  # GET /parcels/1/edit
  def edit
    @parcel = Parcel.find(params[:id])
  end

  # POST /parcels
  # POST /parcels.json
  def create
    @parcel = Parcel.new(params[:parcel])

    #Rails.logger.info "*****************"
    #Rails.logger.info @parcel.title
    #Rails.logger.info params[:parcel]
    #Rails.logger.info "*****************"

    respond_to do |format|
      if @parcel.save
        format.html { redirect_to @parcel, notice: 'Parcel was successfully created.' }
        format.json { render json: @parcel, status: :created, location: @parcel }
      else
        format.html { render action: "new" }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parcels/1
  # PUT /parcels/1.json
  def update
    @parcel = Parcel.find(params[:id])

    respond_to do |format|

      if @parcel.update_attributes(params[:parcel])
        format.html { redirect_to @parcel, notice: 'Parcel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parcels/1
  # DELETE /parcels/1.json
  def destroy
    #@parcel = Parcel.find(params[:id])
    #@parcel.destroy

    respond_to do |format|
      format.html { redirect_to parcels_url }
      format.json { head :no_content }
    end
  end
end

app/views/parcels/_form.html.haml
= simple_form_for(@parcel) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :short_description
    = f.input :description
    %br
    %br
    latitude
    = f.input :latitude
    longitude
    = f.input :longitude
    %br
    %br
    Icon name for map
    = f.input :icon
    Image name for show page
    = f.input :imagename
    %br
    %br
  .form-actions
    = f.button :submit

app/views/parcels/edit.html.haml
%h1 Editing parcel

= render 'form'

= link_to 'Show', @parcel
\|
= link_to 'Back', parcels_path

app/views/parcels/index.html.haml
#map
= content_tag "div", id: "parcel_content", data: {parcels: @parcels} do end

app/views/parcels/new.html.haml
%h1 New parcel

= render 'form'

= link_to 'Back', parcels_path

app/views/parcels/show.html.haml
- data_name = "Protect #{@parcel.title}."
#parcel
  #backbutton
    =link_to_function "Back", "history.back()", :id=> 'button'
  /%script{"data-amount" => "0.01","data-name" => data_name, "data-button" => "donate","data-currency" => "USD","data-env" => "www","data-shipping" => "0","data-tax" => "0",:src => "../paypal-button.min.js?merchant=acrecare@amazonaid.org"}
  #title
    =image_tag "#{@parcel.icon}"
    #{@parcel.title}
  #protectbutton
    =link_to "Protect #{@parcel.title}!", '/donations/new', :id=> 'yellowbutton'
  %br
  %br

  #description_content
    =@parcel.short_description.html_safe
    =@parcel.description.html_safe


  /  #short_description
  /    = "#{@parcel.short_description}"
  /
  /  #description_top
  /    = "#{@parcel.short_description} #{@parcel.description}"



  #image
    -if @parcel.imagename.include? 'png' or @parcel.imagename.include? 'jpg' or @parcel.imagename.include? 'jpeg'
      =image_tag @parcel.imagename
    -else
      %iframe{:id => "video",:allowfullscreen => "", :frameborder => "0", :mozallowfullscreen => "yes", :src =>  @parcel.imagename, :webkitallowfullscreen => "yes"}


  #description_bottom
    = "#{@parcel.description}"

  %br
  =link_to_function "Back", "history.back()", :id=> 'button'