config/routes.rb
AcreCare::Application.routes.draw do

  devise_for :admins

  resources :donations


  resources :parcels

  root :to => "parcels#index"

  match "/thanks" => "pages#thanks"
  match "/certificate" => "pages#certificate"
  match "/ecard" => "pages#ecard"
  match "/about" =>"pages#about"
  match "/donate" => "pages#donate"

end

app/views/pages/about.html.haml
#about
  #panel
    #container
      =image_tag 'crowdsource.png'
      %br
      %br
      %b
        ABOUT THE AMAZON AID FOUNDATION.
      The Amazon Aid Foundation is a 501(c)3 nonprofit with a mission to bring awareness and environmental sustainability for the Amazon rainforest through multi-media educational materials while assisting partners on the ground who provide solutions. Visit us at
      =link_to 'www.amazonaid.org','http://www.amazonaid.org'
      for more information.
      %br
      %br
      %b
        Why Acre+Care?
      Acre+Care is Amazon Aid Foundation’s revolutionary system for direct private protection of the Amazon rainforests. For $40 you can adopt and protect an acre through our NASA geospacial mapping system. 100 percent of your donation to the Amazon Aid Foundation helps fund the supervision and operation of the 100,000 acres in the Madre De Dios region – the headwaters of the Amazon. This includes the funding of park guards, government protection, concession staff, and management of the area.
      %br
      %br
      %b
        Why The Amazon?
      The Amazon is home to more plants, animals and trees than any other place in the world. The Amazon also helps regulate weather systems, carries 20 percent of the planets fresh water, is a huge repository for foods and medicines, is one of the world's major carbon sinks, and is the home to a rich array of indigenous peoples. Unfortunately, the burning of trees, not only destroys this valuable habitat, compromising the peoples and the species that live there, but releases the carbon stored in the trees trunks branches and roots, adding approximately 20% of all yearly carbon emissions. Some experts say that at the current rate of destruction the amazon could be gone in 40 years.
      %br
      %br
      %b
        Why Is The Amazon Being Destroyed?
      The rise in international pressure for natural resources has led to a wide range of extractive activities that threaten the Amazon. These include mining and oil expansion, developmental pressures from road construction, land conversion to fields or pasture, and logging. While the landholders in the Amazon strive to protect their forests from this type of conversion, finding equally financially lucrative uses for their land is an extremely difficult task.

    #container
      %br
      %br
      %b
        How Does Your Money Help?
      Protecting habitat is one of the most important things you can do. Your donations go into an interest bearing fund; The interest is used to protect the Amazon in Madre de Dios. Based on the past several years of expenses related to protecting the specified lands, we have calculated that if each of the 100,000 acres were adopted at $40 per acre, the interest from those donations would be enough to manage and protect these healthy Amazonia forests for at least 40 years. 100 percent of your donation is at work when you adopt an acre through ACRE+CARE.
      %br
      Protecting acres are hard. And expensive to do. The Amazon is valuable, and people take the precious natural resources for themselves. If we do not pay to protect the forests, then the Amazon will disappear. So help us keep the trees standing. Adapt an acre through Acre+Care and protect the Amazon one tree at a time.
      %br
      %br
      %b
        WHY THESE ACRES?
      One of the Amazon Aid Foundation’s (AAF) main goals is to maintain partnerships with Amazon conservation organizations that have a dedicated history of preservation in the area. For our pilot project, we are working with the Amazon Conservation Association (ACA) and its sister organization in Peru, la Asociación para la Conservación de la Cuenca Amazónica (ACCA). These organizations’ shared mission is to protect and scientifically study these rich forests. For over 15 years the scientists from the Amazon Conservation Association have lived and learned about the wide variety of plants, animals and peoples that call the Amazon home. Great rivers, like the Los Amigos River, trickle down from the adjacent Andes Mountains. This area also holds the important reserve for un-contacted indigenous groups, the Territorial Reserve of Madre de Dios, and also houses trees that are still standing within 100,000 acres of old-growth Amazonian forest, plants and animals, terrestrial and aquatic habitats like palm swamps, oxbow lakes, bamboo thickets and various types of flooded and non-flooded forests. Today, our partnership with ACA-ACCA does more than just protect. Together, we aim to foster more research, education and empowerment among the Latin American people so they can benefit from this sacred area and act as long-term guardians, mentors and conservation planners in the region.
      =image_tag 'generalfund.png'

    #back
      =link_to_function "Back", "history.back()", :id=> 'button'

app/views/pages/index.html.haml
#thanks
  #container
    #thankyoumessage
      Thank You
    #certificate
      %center
        = link_to image_tag("certificate.jpg") , certificate_path ;
        %br
        .fb-like{"data-href" => "http://www.amazonaid.org/", "data-send" => "false", "data-show-faces" => "true", "data-width" => "0"}
        %br
        %a.twitter-share-button{"data-size" => "large", "data-text" => "I just donated $40 to help AmazonAid preserve the natural beauty of the rainforest", "data-url" => "http://www.amazonaid.org/", :href => "https://twitter.com/share"} Tweet

app/views/pages/thanks.html.haml
#thanks
  %p
  #light.white_content
    =image_tag '4.gif', :id => 'spinner'
  #fade.black_overlay
    #text
      Generating Certificate PDF
  #share
    %center
      %br
      #social_media_links
        .fb-like{"data-font" => "tahoma", "data-href" => "http://www.amazonaid.org/", "data-layout" => "button_count", "data-send" => "false", "data-show-faces" => "false", "data-width" => "450"}
        %a.twitter-share-button{"data-count" => "horizontal", "data-text" => "Named an acre of Amazon rain forest for protection and conservation", "data-url" => "http://www.amazonaid.org/", "data-via" => "", :href => "https://twitter.com/share"} Tweet
        %g:plusone

  #thankyoumessage
    %h1 Thank You

  #paypalmessage
    Your transaction has been completed, and a receipt for your donation has been emailed to you. You may log into your account at www.paypal.com/us to view details of this transaction.
    %br
    %br

  #certificateform
    #form
      #text
        /eCard Detail
        = simple_form_for :certificate do |f|  #see certificate.js - pages#certificate
          .form-inputs
            = 'ACRE NAME'
            = f.input :acrename, :placeholder => 'NAME THE ACRES WHICH YOU SAVED', :input_html => { :value =>  @donation.acrename}, :label => false, :required=> false

            = 'eCard RECIPIENT FIRST NAME'
            = f.input :recipient_firstname, :placeholder => '', :label => false,  :input_html => { :value =>  @donation.recipient_firstname}

            = 'eCard RECIPIENT LAST NAME'
            = f.input :recipient_lastname, :placeholder => '', :label => false,  :input_html =>  { :value =>  @donation.recipient_lastname}, :required=> false

            = 'eCard RECIPIENT EMAIL ADDRESS'
            = f.input :recipientemail, :placeholder => '', :input_html => { :value =>  @donation.recipient_email}, :label => false, :required=> false

            /= 'PERSONALIZED MESSAGE FOR ECARD'
            /= f.text_area :personalizedmessage, :placeholder => '', :label => false, :required=> false
          .form-actions
            = f.button :submit, 'Download Certificate', :class=> 'generate_btn'
            = f.button :submit, 'Email Certificate eCard', :class=> 'ecard_btn'

    #share
      %center
        %br
        #social_media_links
          .fb-like{"data-font" => "tahoma", "data-href" => "http://www.amazonaid.org/", "data-layout" => "button_count", "data-send" => "false", "data-show-faces" => "false", "data-width" => "450"}
          %a.twitter-share-button{"data-count" => "horizontal", "data-text" => "Named an acre of Amazon rain forest for protection and conservation", "data-url" => "http://www.amazonaid.org/", "data-via" => "", :href => "https://twitter.com/share"} Tweet
          %g:plusone
        %br
        %br
        %br
        %br