config/routes.rb
AcreCare::Application.routes.draw do

  devise_for :admins

  resources :donations


  resources :parcels

  root :to => "parcels#index"

  match "/thanks" => "pages#thanks"
  match "/certificate" => "pages#certificate"
  match "/ecard" => "pages#ecard"
  match "/about" =>"pages#about"
  match "/donate" => "pages#donate"

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  attr_accessible :acrename,
                  :donor_email,
                  :donor_firstname,
                  :donor_lastname,
                  :recipient_firstname,
                  :recipient_lastname,
                  :message,
                  :numberofacres,
                  :gift,
                  :gift_sender_name,
                  :recipient_email,
                  :parcel
  validates_presence_of :donor_firstname, :donor_lastname,  :donor_email


end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_filter :authenticate_admin!, :except => [:new,:edit,:update, :create, :show]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donations }
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @donation = Donation.find(params[:id])
    cookies[:donation] = params[:id]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
    @donation = Donation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(params[:donation])

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: '' }
        format.json { render json: @donation, status: :created, location: @donation }
      else
        format.html { render action: "new" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to @donation, notice: '' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.haml
%p#notice= notice
- parcel_name =  cookies[:parcel_name]

#donation
  %p
  #donationlabel
    %h1
  #donationmessage
    %h3 Acre certificate and ecard confirmation details will be handle upon return from paypal after checkout
    %h3 click here to see example Acre Certificate

  #donationform
    #form
      #text
        /Donation Detail
        - unless parcel_name.nil? || parcel_name.empty?
          #parcel_name_label
            /= parcel_name

        = simple_form_for @donation, :html => {:validate => 'true'} do |f|  #see certificate.js - pages#certificate
          .form-inputs
            = f.input :parcel, :as => :hidden, :input_html => { :value => parcel_name }
            = f.input :donor_firstname, :placeholder => 'YOUR FIRST NAME', :label => false, :required=> true
            = f.input :donor_lastname, :placeholder => 'YOUR LAST NAME', :label => false, :required=> true
            = f.input :donor_email, :placeholder => 'YOUR EMAIL ADDRESS', :label => false, :required=> true
            /-unless(data_name.blank?)
            /  = f.collection_select :parcel, Parcel.all, :title, :title , :selected => data_name
            %br
            = f.select :numberofacres, options_for_select([['Save One Acre For Forty Years: $50',1],['Save Two Acres For Forty Years: $100',2]])
            %br
            %br
            %br
            = f.button :submit, 'Next', :id => :nextbutton
        /#donate
        /%script{"data-amount" => "0.01","data-name" => data_name, "data-button" => "donate","data-currency" => "USD","data-env" => "www","data-shipping" => "0","data-tax" => "0",:src => "../paypal-button.min.js?merchant=acrecare@amazonaid.org"}
        %br
        %br
        %br
    #backbutton
      =link_to "Back",'/', :id=> 'button'
    %br
    %br

app/views/donations/edit.html.haml
= render 'form'

app/views/donations/index.html.haml
%h1 Listing donations

%table
  %h6
    - @donations.each do |donation|
      %tr
        %td= donation.donor_firstname
        %td= donation.donor_lastname
        %td= donation.donor_email
        %td= donation.acrename
        %td= donation.donor_firstname
        %td= donation.donor_lastname
        %td= donation.donor_email
        %td= donation.message
        %td= link_to 'Show', donation
        %td= link_to 'Edit', edit_donation_path(donation)
        %td= link_to 'Destroy', donation, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Donation', new_donation_path

app/views/donations/new.html.haml
= render 'form'

app/views/donations/show.html.haml
#show_donation
  #donationform
    #form
      #text
        %p
          %b Your Name:
          = "#{@donation.donor_firstname} #{@donation.donor_lastname}"
          %br
          %b Your email:
          = @donation.donor_email
          %br
          %b Pledge:
          = "$#{@donation.numberofacres*50} to protect #{@donation.numberofacres} acre for forty years"

          %br
          -unless @donation.parcel.empty?
            %b Area of interest:
            ="#{@donation.parcel}"
          %br
          %br
          %b Please use paypal to securely make your donation

          %br
          %br
          = link_to 'Back', edit_donation_path(@donation)
          %br
          %br
          -product = "$#{@donation.numberofacres*50} to protect #{@donation.numberofacres} acres in the Amazon Rainforest for forty years"

          %script{"data-amount" => @donation.numberofacres*50,"data-name" => product, "data-button" => "donate","data-currency" => "USD","data-env" => "www","data-shipping" => "0","data-tax" => "0",:src => "../paypal-button.min.js?merchant=acrecare@amazonaid.org"}